name: Multi-Service CI/CD to EKS

on:
  push:
    branches: [ main ]
  workflow_dispatch:  

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [product-service, order-service, user-service]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # AWS Login
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Connect to EKS
    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name quickart-eks --region $AWS_REGION

    # Debug (keep this until stable)
    - name: Debug variables
      run: |
        echo "SERVICE=${{ matrix.service }}"
        echo "DOCKERHUB_USER=${{ secrets.DOCKERHUB_USERNAME }}"

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    # Build JAR (IMPORTANT)
    - name: Build JAR
      run: mvn clean package -DskipTests
      working-directory: ./${{ matrix.service }}

    # Build & push Docker image
    - name: Build & Push Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:${{ github.sha }} ./${{ matrix.service }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:${{ github.sha }}

    # Install Helm
    - name: Install Helm
      run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    # Deploy to EKS
    - name: Deploy to EKS
      run: |
        helm upgrade --install ${{ matrix.service }} ./quickart-chart \
        -f quickart-chart/values/${{ matrix.service }}.yaml \
        --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }} \
        --set image.tag=${{ github.sha }} \
        -n quickart --create-namespace
