name: Build Push Update Helm

on:
  push:
    branches:
      - main

jobs:

  detect-changes:
    runs-on: ubuntu-latest

    outputs:
      product: ${{ steps.filter.outputs.product }}
      order: ${{ steps.filter.outputs.order }}
      user: ${{ steps.filter.outputs.user }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Detect Changed Services
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            product:
              - 'product-service/**'

            order:
              - 'order-service/**'

            user:
              - 'user-service/**'

  build-and-deploy:
    needs: detect-changes

    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - service: product-service
            changed: ${{ needs.detect-changes.outputs.product }}

          - service: order-service
            changed: ${{ needs.detect-changes.outputs.order }}

          - service: user-service
            changed: ${{ needs.detect-changes.outputs.user }}

    if: matrix.changed == 'true'

    steps:

      #################################################
      # CHECKOUT
      #################################################

      - name: Checkout Application Repo
        uses: actions/checkout@v4

      #################################################
      # JAVA SETUP
      #################################################

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      #################################################
      # BUILD SPRINGBOOT APP
      #################################################

      - name: Build Service
        working-directory: ${{ matrix.service }}
        run: |
          mvn clean package -DskipTests

      #################################################
      # DOCKER LOGIN
      #################################################

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      #################################################
      # BUILD IMAGE
      #################################################

      - name: Build Docker Image
        working-directory: ${{ matrix.service }}
        run: |
          docker build \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:${{ github.sha }} \
          .

      #################################################
      # PUSH IMAGE
      #################################################

      - name: Push Docker Image
        run: |
          docker push \
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:${{ github.sha }}

      #################################################
      # CLONE GITOPS REPO
      #################################################

      - name: Clone quickart-deploy Repo
        run: |
          git clone https://${{ secrets.GIT_TOKEN }}@github.com/YOUR_GITHUB_USERNAME/quickart-deploy.git

      #################################################
      # INSTALL YQ
      #################################################

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      #################################################
      # UPDATE HELM VALUES
      #################################################

      - name: Update Helm values.yaml
        run: |
          cd quickart-deploy

          yq -i '
          .image.repository = "${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}" |
          .image.tag = "${{ github.sha }}"
          ' helm-charts/${{ matrix.service }}/values.yaml

          cat helm-charts/${{ matrix.service }}/values.yaml

      #################################################
      # COMMIT CHANGES
      #################################################

      - name: Commit Changes
        run: |
          cd quickart-deploy

          git config user.email "github-actions@github.com"
          git config user.name "github-actions"

          git add .

          git commit -m "Update ${{ matrix.service }} image to ${{ github.sha }}" \
          || echo "No changes"

      #################################################
      # PUSH CHANGES
      #################################################

      - name: Push Changes
        run: |
          cd quickart-deploy

          git push
