name: Enterprise Microservices CI/CD

on:
  push:
    branches:
      - main

jobs:

#########################################################
# DETECT CHANGES
#########################################################

  detect-changes:
    runs-on: ubuntu-latest

    outputs:
      product: ${{ steps.filter.outputs.product }}
      order: ${{ steps.filter.outputs.order }}
      user: ${{ steps.filter.outputs.user }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Detect Changed Services
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            product:
              - 'product-service/**'

            order:
              - 'order-service/**'

            user:
              - 'user-service/**'

#########################################################
# BUILD SERVICES
#########################################################

  build-services:
    needs: detect-changes

    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - product-service
          - order-service
          - user-service

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      #################################################
      # DETERMINE IF SERVICE CHANGED
      #################################################

      - name: Set Change Variable
        id: changed
        run: |

          if [[ "${{ matrix.service }}" == "product-service" ]]; then
            echo "changed=${{ needs.detect-changes.outputs.product }}" >> $GITHUB_OUTPUT

          elif [[ "${{ matrix.service }}" == "order-service" ]]; then
            echo "changed=${{ needs.detect-changes.outputs.order }}" >> $GITHUB_OUTPUT

          elif [[ "${{ matrix.service }}" == "user-service" ]]; then
            echo "changed=${{ needs.detect-changes.outputs.user }}" >> $GITHUB_OUTPUT
          fi

      #################################################
      # JAVA SETUP
      #################################################

      - name: Setup Java
        if: steps.changed.outputs.changed == 'true'
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      #################################################
      # BUILD APPLICATION
      #################################################

      - name: Build SpringBoot App
        if: steps.changed.outputs.changed == 'true'
        working-directory: ${{ matrix.service }}
        run: |
          mvn clean package -DskipTests

      #################################################
      # DOCKER LOGIN
      #################################################

      - name: Docker Login
        if: steps.changed.outputs.changed == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #################################################
      # BUILD IMAGE
      #################################################

      - name: Build Docker Image
        if: steps.changed.outputs.changed == 'true'
        working-directory: ${{ matrix.service }}
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:${{ github.sha }} .

      #################################################
      # PUSH IMAGE
      #################################################

      - name: Push Docker Image
        if: steps.changed.outputs.changed == 'true'
        run: |
          docker push \
          ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:${{ github.sha }}

#########################################################
# SINGLE GITOPS UPDATE JOB
#########################################################

  update-gitops:
    needs:
      - detect-changes
      - build-services

    runs-on: ubuntu-latest

    steps:

      #################################################
      # CLONE GITOPS REPO
      #################################################

      - name: Clone quickart-deploy Repo
        run: |
          git clone https://${{ secrets.GIT_TOKEN }}@github.com/YOUR_GITHUB_USERNAME/quickart-deploy.git

      #################################################
      # INSTALL YQ
      #################################################

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      #################################################
      # UPDATE PRODUCT SERVICE
      #################################################

      - name: Update Product Service
        if: needs.detect-changes.outputs.product == 'true'
        run: |
          cd quickart-deploy

          yq -i '
          .image.tag = "${{ github.sha }}"
          ' helm-charts/product-service/values.yaml

      #################################################
      # UPDATE ORDER SERVICE
      #################################################

      - name: Update Order Service
        if: needs.detect-changes.outputs.order == 'true'
        run: |
          cd quickart-deploy

          yq -i '
          .image.tag = "${{ github.sha }}"
          ' helm-charts/order-service/values.yaml

      #################################################
      # UPDATE USER SERVICE
      #################################################

      - name: Update User Service
        if: needs.detect-changes.outputs.user == 'true'
        run: |
          cd quickart-deploy

          yq -i '
          .image.tag = "${{ github.sha }}"
          ' helm-charts/user-service/values.yaml

      #################################################
      # COMMIT & PUSH ONCE
      #################################################

      - name: Commit and Push Changes
        run: |
          cd quickart-deploy

          git config user.email "github-actions@github.com"
          git config user.name "github-actions"

          git add .

          git commit -m "Update image tags to ${{ github.sha }}" \
          || echo "No changes"

          git push
